module.exports = function() {

  let apiResult = {
    "count": 6,
    "next": null,
    "previous": null,
    "results": [
      {
        "id": 7,
        "type": "put",
        "reference": {
          "id": 5,
          "reference": "50535",
          "model_name": "Omega Moonphase",
          "brand_name": "Omega",
          "price": 24900
        },
        "price": "24900.00",
        "raise_price": null,
        "insert_date": "1537274713",
        "closed_date": "1537277112",
        "call_1_start_date": "1537274712",
        "call_1_end_date": "1537275312",
        "call_1_end_selection": "1537275912",
        "call_2_start_date": "1537276512",
        "call_2_end_date": "1537277112",
        "call_2_end_selection": "1537277712",
        "matched_price": null,
        "payment_expiry": "1537278312",
        "status": "winner_selected",
        "won_by_this_user": false,
        "owned_by_this_user": false,
        "owner_address": {
          "city": "Milan",
          "country": "Italy"
        },
        "joined_by_this_user": false,
        "second_call_joined_by_this_user": false,
        "first_call_selection_for_this_user": false,
        "first_call_selection_completed": true,
        "server_timestamp": 1551366098,
        "time_remain": 0,
        "first_call_selection_date": "1537275483",
        "main_image": null
      },
      {
        "id": 9,
        "type": "put",
        "reference": {
          "id": 5,
          "reference": "50535",
          "model_name": "Omega Moonphase",
          "brand_name": "Omega",
          "price": 24900
        },
        "price": "24900.00",
        "raise_price": null,
        "insert_date": "1537277199",
        "closed_date": "1537277788",
        "call_1_start_date": "1537277187",
        "call_1_end_date": "1537277787",
        "call_1_end_selection": "1537278387",
        "call_2_start_date": "1537278987",
        "call_2_end_date": "1537279587",
        "call_2_end_selection": "1537280187",
        "matched_price": null,
        "payment_expiry": "1537280787",
        "status": "decayed_first_call",
        "won_by_this_user": false,
        "owned_by_this_user": false,
        "owner_address": {
          "city": "Milan",
          "country": "Italy"
        },
        "joined_by_this_user": false,
        "second_call_joined_by_this_user": false,
        "first_call_selection_for_this_user": false,
        "first_call_selection_completed": false,
        "server_timestamp": 1551366098,
        "time_remain": 0,
        "first_call_selection_date": null,
        "main_image": null
      },
      {
        "id": 15,
        "type": "put",
        "reference": {
          "id": 5,
          "reference": "50535",
          "model_name": "Omega Moonphase",
          "brand_name": "Omega",
          "price": 24900
        },
        "price": "24900.00",
        "raise_price": null,
        "insert_date": "1539155555",
        "closed_date": "1539156180",
        "call_1_start_date": "1539155580",
        "call_1_end_date": "1539156180",
        "call_1_end_selection": "1539156480",
        "call_2_start_date": "1539156480",
        "call_2_end_date": "1539157080",
        "call_2_end_selection": "1539157680",
        "matched_price": null,
        "payment_expiry": "1539158280",
        "status": "decayed_first_call",
        "won_by_this_user": false,
        "owned_by_this_user": false,
        "owner_address": {
          "city": "Milan",
          "country": "Italy"
        },
        "joined_by_this_user": false,
        "second_call_joined_by_this_user": false,
        "first_call_selection_for_this_user": false,
        "first_call_selection_completed": false,
        "server_timestamp": 1551366098,
        "time_remain": 0,
        "first_call_selection_date": null,
        "main_image": null
      },
      {
        "id": 16,
        "type": "put",
        "reference": {
          "id": 5,
          "reference": "50535",
          "model_name": "Omega Moonphase",
          "brand_name": "Omega",
          "price": 24900
        },
        "price": "24900.00",
        "raise_price": null,
        "insert_date": "1539618714",
        "closed_date": "1539619292",
        "call_1_start_date": "1539618692",
        "call_1_end_date": "1539619292",
        "call_1_end_selection": "1539619592",
        "call_2_start_date": "1539619592",
        "call_2_end_date": "1539620192",
        "call_2_end_selection": "1539620792",
        "matched_price": null,
        "payment_expiry": "1539621392",
        "status": "decayed_first_call",
        "won_by_this_user": false,
        "owned_by_this_user": false,
        "owner_address": {
          "city": "Milan",
          "country": "Italy"
        },
        "joined_by_this_user": false,
        "second_call_joined_by_this_user": false,
        "first_call_selection_for_this_user": false,
        "first_call_selection_completed": false,
        "server_timestamp": 1551366098,
        "time_remain": 0,
        "first_call_selection_date": null,
        "main_image": null
      },
      {
        "id": 18,
        "type": "put",
        "reference": {
          "id": 4,
          "reference": "01.420.0006.3.091",
          "model_name": "True Thinline Nature",
          "brand_name": "Rado",
          "price": 2070
        },
        "price": "2070.00",
        "raise_price": null,
        "insert_date": "1539865344",
        "closed_date": "1539952328",
        "call_1_start_date": "1539951728",
        "call_1_end_date": "1539952328",
        "call_1_end_selection": "1539952628",
        "call_2_start_date": "1539952628",
        "call_2_end_date": "1539953228",
        "call_2_end_selection": "1539953828",
        "matched_price": null,
        "payment_expiry": "1539954428",
        "status": "decayed_first_call",
        "won_by_this_user": false,
        "owned_by_this_user": false,
        "owner_address": {
          "city": "Milan",
          "country": "Italy"
        },
        "joined_by_this_user": false,
        "second_call_joined_by_this_user": false,
        "first_call_selection_for_this_user": false,
        "first_call_selection_completed": false,
        "server_timestamp": 1551366098,
        "time_remain": 0,
        "first_call_selection_date": null,
        "main_image": null
      },
      {
        "id": 40,
        "type": "put",
        "reference": {
          "id": 6,
          "reference": "50505",
          "model_name": "Omega Time",
          "brand_name": "Omega",
          "price": 14150
        },
        "price": "34500.00",
        "raise_price": null,
        "insert_date": "1543862866",
        "closed_date": "1543864200",
        "call_1_start_date": "1543863600",
        "call_1_end_date": "1543864200",
        "call_1_end_selection": "1543864500",
        "call_2_start_date": "1543864500",
        "call_2_end_date": "1543865100",
        "call_2_end_selection": "1543865700",
        "matched_price": null,
        "payment_expiry": "1543866300",
        "status": "first_call",
        "won_by_this_user": false,
        "owned_by_this_user": false,
        "owner_address": {
          "city": "Milan",
          "country": "Italy"
        },
        "joined_by_this_user": false,
        "second_call_joined_by_this_user": false,
        "first_call_selection_for_this_user": false,
        "first_call_selection_completed": false,
        "server_timestamp": 1551366098,
        "time_remain": 0,
        "first_call_selection_date": null,
        "main_image": null
      }
    ]
  }

  return apiResult
}
